import logging
import time
import uuid
from typing import Callable

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .context import request_id_var, session_id_var, trace_id_var, user_id_var
from .settings import CommonSettings

logger = logging.getLogger(__name__)


class RequestContext:
    """
    Middleware that initializes request-scoped context
    for each incoming HTTP request.

    Sets request, trace, session, and user IDs in context variables
    for logging and tracing purposes.
    """
    def __init__(self, app: Callable):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        start_time = time.perf_counter()

        headers = dict(scope["headers"])

        method = scope.get("method", "").upper()
        path = scope.get("path", "")

        request_id_bytes = headers.get(
            b"x-request-id") or str(uuid.uuid4()).encode()
        trace_id_bytes = headers.get(
            b"x-trace-id") or str(uuid.uuid4()).encode()

        t1 = request_id_var.set(request_id_bytes.decode("utf-8"))
        t2 = trace_id_var.set(trace_id_bytes.decode("utf-8"))

        response_status = 500

        async def send_wrapper(message):
            nonlocal response_status
            if message["type"] == "http.response.start":
                response_status = message.get("status", 500)
                process_time = time.perf_counter() - start_time

                headers = message.setdefault("headers", [])
                headers.append((b"x-request-id", request_id_bytes))
                headers.append((b"x-trace-id", trace_id_bytes))
                headers.append((b"x-process-time", str(process_time).encode()))

                current_session_id = session_id_var.get()
                if current_session_id:
                    headers.append(
                        (b"x-session-id", current_session_id.encode())
                        )

                current_user_id = user_id_var.get()
                if current_user_id:
                    headers.append((b"x-user-id", current_user_id.encode()))

            await send(message)

        try:
            await self.app(scope, receive, send_wrapper)
        finally:
            process_time = time.perf_counter() - start_time
            logger.info(
                "Request completed",
                extra={
                    "method": method,
                    "path": path,
                    "status": response_status,
                    "process_time": process_time,
                    "request_id": request_id_var.get(),
                    "trace_id": trace_id_var.get(),
                }
            )

            request_id_var.reset(t1)
            trace_id_var.reset(t2)


def setup_middleware(app: FastAPI, settings: CommonSettings) -> None:
    """
    Set up middleware for the FastAPI microservices.

    Middleware is added in the following order:
    1. RequestContext: Handles request and trace IDs, session ID, and user ID.
    - request_id_var, trace_id_var, session_id_var, and user_id_var
    are set in the context for each request.
    - The middleware also logs the request completion with relevant details.
    2. CORSMiddleware: Handles Cross-Origin Resource Sharing (CORS) settings.
    - It is kept as the outermost middleware to ensure proper handling of
    CORS headers to all responses, including
    those generated by other middleware.

    Execution:
    Middleware is executed in reverse order of addition, so
    the last added middleware is executed first.

    Args:
        - app (FastAPI): The FastAPI application instance.
        - settings (CommonSettings): The settings object
        containing CORS configurations.
    """
    app.add_middleware(RequestContext)
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.cors_allow_origins,
        allow_credentials=settings.cors_allow_credentials,
        allow_methods=settings.cors_allow_methods,
        allow_headers=settings.cors_allow_headers,
        expose_headers=settings.cors_expose_headers
    )
